const API = window.FRONTEND_API_BASE_URL || localStorage.getItem('apiBase') || 'https://hireflow-ai-production-ed0f.up.railway.app';
const state = {token: localStorage.getItem('token'), userId: localStorage.getItem('userId'), role: localStorage.getItem('role'), authMode:'login', jobs:[], applications:[]};
const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(msg){$('toast').textContent=msg;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),3500)}
async function api(path,opts={}){const headers=opts.headers||{};if(state.token)headers.Authorization=`Bearer ${state.token}`;const r=await fetch(API+path,{...opts,headers});let data={};try{data=await r.json()}catch{}if(r.status===401){localStorage.clear();state.token=null;state.userId=null;state.role=null;$('authView').classList.remove('hidden');$('appView').classList.add('hidden');toast('Session expired. Please sign in again.');throw new Error('Session expired. Please sign in again.')}if(!r.ok||data.error)throw new Error(data.detail||data.error||`Request failed (${r.status})`);return data}
function setAuthMode(mode){state.authMode=mode;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.auth===mode));$('nameLabel').classList.toggle('hidden',mode==='login');$('phoneLabel').classList.toggle('hidden',mode==='login')}
document.querySelectorAll('.tab').forEach(x=>x.onclick=()=>setAuthMode(x.dataset.auth));
$('authForm').onsubmit=async e=>{e.preventDefault();try{const path=state.authMode==='login'?'/login':'/signup';const body=state.authMode==='login'?{email:$('email').value,password:$('password').value}:{full_name:$('fullName').value,phone:$('phone').value,email:$('email').value,password:$('password').value};const d=await api(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(state.authMode==='signup'){toast('Account created. Confirm your email, then sign in.');setAuthMode('login');return}state.token=d.access_token;state.userId=d.user_id;state.role=d.role;localStorage.setItem('token',state.token);localStorage.setItem('userId',state.userId);localStorage.setItem('role',state.role||'');await boot()}catch(e){toast(e.message)}};
function logout(){localStorage.clear();location.reload()} $('logoutBtn').onclick=logout; $('refreshBtn').onclick=boot;
function nav(items){$('nav').innerHTML=items.map((x,i)=>`<button class="${i===0?'active':''}" data-view="${x[0]}">${x[1]}</button>`).join('');document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.view)})}
async function boot(){if(!state.token){$('authView').classList.remove('hidden');$('appView').classList.add('hidden');return}$('authView').classList.add('hidden');$('appView').classList.remove('hidden');$('identity').textContent=`Signed in · ${state.role||'user'}`;nav(state.role==='admin'?[['dashboard','Dashboard'],['create','Create job'],['jobs','Jobs'],['admin-applications','Applications'],['recruiters','Recruiters']]:state.role==='recruiter'?[['recruiter','Assigned jobs'],['applications','Applications']]:[['home','Overview'],['jobs','Open jobs'],['applications','My applications'],['cv','Manage CV']]);try{await loadRole();render(state.role==='admin'?'dashboard':state.role==='recruiter'?'recruiter':'home')}catch(e){toast(e.message)}}
async function loadRole(){const d=await api('/jobs');state.jobs=d.jobs||[];if(state.role==='candidate'){const a=await api('/my-applications');state.applications=a.applications||[]}}
function render(view){const fn={home:renderHome,jobs:renderJobs,applications:renderApplications,cv:renderCV,create:renderCreateJob,dashboard:renderDashboard,'admin-applications':renderAdminApplications,recruiter:renderRecruiter,recruiters:renderRecruiters}[view]||renderHome;fn()}
function renderCreateJob(){ $('welcomeTitle').textContent='Create a job';$('welcomeText').textContent='New jobs start as drafts and can be opened from the dashboard.';$('content').innerHTML='<div class="card"><form id="jobForm" class="form-grid"><label>Title<input name="title" required></label><label>Company<input name="company_name" required></label><label>Department<input name="department" required></label><label>Location<input name="location" required></label><label>Employment type<input name="employment_type" placeholder="full-time" required></label><label>Last date<input name="last_date" type="date" required></label><label>Openings<input name="openings" type="number" min="1" value="1" required></label><label>Salary min<input name="salary_min" type="number"></label><label>Salary max<input name="salary_max" type="number"></label><label class="wide">Description<textarea name="description" rows="4" required></textarea></label><label class="wide">Requirements<textarea name="requirements" rows="4" required></textarea></label><button class="primary wide" type="submit">Create draft job</button></form></div>';$("jobForm").onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));data.openings=Number(data.openings);data.salary_min=data.salary_min?Number(data.salary_min):null;data.salary_max=data.salary_max?Number(data.salary_max):null;try{const d=await api('/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});toast(d.message||'Job created');render('dashboard')}catch(err){toast(err.message)}}}
function renderCV(){ $('welcomeTitle').textContent='Manage CV';$('welcomeText').textContent='Upload a PDF CV up to 2 MB. Your current CV stays private.';$('content').innerHTML='<div class="card"><h2>Private CV</h2><p class="muted">PDF only · maximum 2 MB</p><form id="cvForm"><label>Choose PDF<input id="cvFile" type="file" accept="application/pdf,.pdf" required></label><button class="primary" type="submit">Upload or replace CV</button></form></div>';$("cvForm").onsubmit=async e=>{e.preventDefault();const f=$("cvFile").files[0];if(!f||f.size>2*1024*1024){toast('Choose a PDF no larger than 2 MB');return}const fd=new FormData();fd.append('file',f);try{const d=await api('/candidate/cv',{method:'POST',body:fd});toast(d.message||'CV uploaded')}catch(err){toast(err.message)}}}
function renderHome(){ $('welcomeTitle').textContent='Welcome back';$('welcomeText').textContent='Your next opportunity is closer than you think.';$('content').innerHTML=`<div class="section-title"><h2>Open roles</h2><button class="secondary" onclick="render('jobs')">View all</button></div><div class="grid">${state.jobs.slice(0,4).map(jobCard).join('')||empty('No open roles right now.')}</div><div class="section-title"><h2>My applications</h2></div>${applicationTable(state.applications)}`}
function jobCard(j){return `<article class="card job-card"><div><h3>${esc(j.title)}</h3><p class="muted">${esc(j.company_name)} · ${esc(j.department)}</p></div><div class="job-meta"><span>${esc(j.location)}</span><span>${esc(j.employment_type)}</span><span>Apply by ${esc(j.last_date)}</span></div><p class="muted">${esc((j.description||'').slice(0,130))}</p><div class="actions"><button class="primary" onclick="applyJob('${j.id}')">Apply now</button><button class="secondary" onclick="showJob('${j.id}')">Details</button></div></article>`}
async function showJob(id){try{const d=await api(`/jobs/${id}`);const j=d.job;$('welcomeTitle').textContent=j.title;$('welcomeText').textContent=`${j.company_name} · ${j.location}`;$('content').innerHTML=`<article class="card"><h2>${esc(j.title)}</h2><p class="muted">${esc(j.company_name)} · ${esc(j.department)} · ${esc(j.employment_type)}</p><div class="job-meta"><span>${esc(j.location)}</span><span>Apply by ${esc(j.last_date)}</span><span>${j.openings} opening(s)</span></div><h3>Description</h3><p>${esc(j.description)}</p><h3>Requirements</h3><p>${esc(j.requirements)}</p><button class="primary" onclick="applyJob('${j.id}')">Apply now</button></article>`}catch(e){toast(e.message)}}
function renderJobs(){ $('welcomeTitle').textContent='Open roles';$('welcomeText').textContent='Browse roles that are currently accepting applications.';$('content').innerHTML=`<div class="grid">${state.jobs.map(jobCard).join('')||empty('No open roles available.')}</div>`}
function applicationTable(items){if(!items?.length)return empty('No applications yet. Browse open roles to get started.');return `<div class="table-wrap"><table><thead><tr><th>Role</th><th>Company</th><th>Status</th><th>Applied</th><th></th></tr></thead><tbody>${items.map(a=>`<tr><td>${esc(a.job?.title||a.job_id)}</td><td>${esc(a.job?.company_name||'')}</td><td><span class="badge">${esc(a.status)}</span></td><td>${esc(a.applied_at||'')}</td><td>${a.status==='applied'||a.status==='shortlisted'?`<button class="secondary danger" onclick="withdraw('${a.id}')">Withdraw</button>`:''}</td></tr>`).join('')}</tbody></table></div>`}
function renderApplications(){ $('welcomeTitle').textContent='My applications';$('welcomeText').textContent='Track every application in one place.';$('content').innerHTML=applicationTable(state.applications)}
function empty(t){return `<div class="empty">${esc(t)}</div>`}
async function applyJob(id){if(!confirm('AI will summarize job-relevant CV information for the recruitment team. AI will not make the hiring decision. Apply now?'))return;try{const r=await api(`/jobs/${id}/apply`,{method:'POST'});toast(r.message||'Application submitted');await boot()}catch(e){toast(e.message)}}
async function withdraw(id){if(!confirm('Withdraw this application?'))return;try{await api(`/my-applications/${id}/withdraw`,{method:'PUT'});toast('Application withdrawn');await boot()}catch(e){toast(e.message)}}
async function renderDashboard(){ $('welcomeTitle').textContent='Admin dashboard';$('welcomeText').textContent='A live view of jobs, recruiters, and the hiring pipeline.';try{const d=await api('/admin/dashboard');$('content').innerHTML=`<div class="grid"><div class="card"><h3>${d.jobs?.length||0}</h3><p class="muted">Jobs</p></div><div class="card"><h3>${d.recruiters?.length||0}</h3><p class="muted">Recruiters</p></div><div class="card"><h3>${d.application_count||0}</h3><p class="muted">Applications</p></div></div><div class="section-title"><h2>Pipeline</h2></div><div class="grid">${Object.entries(d.pipeline_counts||{}).map(([k,v])=>`<div class="card"><h3>${v}</h3><p class="muted">${esc(k)}</p></div>`).join('')}</div><div class="section-title"><h2>Jobs</h2></div><div class="table-wrap"><table><thead><tr><th>Role</th><th>Status</th><th>Openings</th><th>Pipeline</th><th>Action</th></tr></thead><tbody>${(d.jobs||[]).map(j=>`<tr><td>${esc(j.title)}</td><td><span class="badge">${esc(j.status)}</span></td><td>${j.openings}</td><td>${Object.entries(j.pipeline_counts||{}).map(([k,v])=>`${esc(k)} ${v}`).join(' · ')}</td><td>${j.status==='open'?`<button class="secondary danger" onclick="closeJob('${j.id}')">Close</button>`:''}</td></tr>`).join('')}</tbody></table></div>`}catch(e){toast(e.message)}}
async function renderAdminApplications(){ $('welcomeTitle').textContent='Application review';$('welcomeText').textContent='Confirm suitable candidates or reject applications from one place.';try{const d=await api('/admin/applications');const rows=(d.applications||[]).map(a=>`<tr><td>${esc(a.candidate?.full_name||'Candidate')}</td><td>${esc(a.candidate?.email||'')}</td><td>${esc(a.job?.title||'')}</td><td><span class="badge status-${esc(a.status)}">${esc(a.status)}</span></td><td>${a.status==='applied'?`<div class="actions"><button class="primary compact" onclick="adminDecision('${a.id}','shortlisted')">Confirm / Shortlist</button><button class="secondary danger" onclick="adminDecision('${a.id}','rejected')">Reject</button></div>`:'No action'}</td></tr>`).join('');$('content').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Candidate</th><th>Email</th><th>Job</th><th>Status</th><th>Admin decision</th></tr></thead><tbody>${rows||'<tr><td colspan="5">No applications yet.</td></tr>'}</tbody></table></div>`}catch(e){toast(e.message)}}
async function adminDecision(id,status){if(status==='rejected'&&!confirm('Reject this application?'))return;try{const d=await api(`/admin/applications/${id}/decision`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});toast(d.message||'Application updated');renderAdminApplications()}catch(e){toast(e.message)}}
async function closeJob(id){try{await api(`/jobs/${id}/close`,{method:'PUT'});toast('Job closed');render('dashboard')}catch(e){toast(e.message)}}
async function renderRecruiters(){ $('welcomeTitle').textContent='Recruiters';$('welcomeText').textContent='Manage access and active status.';try{const d=await api('/admin/recruiters');$('content').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Active</th><th>Action</th></tr></thead><tbody>${(d.recruiters||[]).map(r=>`<tr><td>${esc(r.full_name)}</td><td>${esc(r.email)}</td><td>${r.is_active?'Yes':'No'}</td><td><button class="secondary" onclick="toggleRecruiter('${r.id}',${!r.is_active})">${r.is_active?'Deactivate':'Reactivate'}</button></td></tr>`).join('')}</tbody></table></div>`}catch(e){toast(e.message)}}
async function toggleRecruiter(id,active){try{await api(`/admin/recruiters/${id}/status`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({is_active:active})});render('recruiters')}catch(e){toast(e.message)}}
async function renderRecruiter(){ $('welcomeTitle').textContent='Recruiter workspace';$('welcomeText').textContent='Review applications for jobs assigned to you.';try{const d=await api('/recruiter/jobs');$('content').innerHTML=`<div class="grid">${(d.jobs||[]).map(j=>`<article class="card"><h3>${esc(j.title)}</h3><p class="muted">${esc(j.company_name||'')}</p><button class="secondary" onclick="loadRecruiterApps('${j.id}')">View applications</button></article>`).join('')||empty('No jobs assigned.')}</div>`}catch(e){toast(e.message)}}
async function loadRecruiterApps(id){try{const d=await api(`/recruiter/jobs/${id}/applications`);$('welcomeTitle').textContent='Applications';$('welcomeText').textContent='Review candidates and move them through the allowed pipeline.';const rows=(d.applications||[]).map(a=>`<tr><td>${esc(a.candidate?.full_name||'Candidate')}</td><td>${esc(a.candidate?.email||'')}</td><td><span class="badge">${esc(a.status)}</span></td><td>${a.has_cv?'Available':'Missing'}</td><td><div class="actions"><select onchange="changeStage('${a.id}',this.value)"><option value="">Change stage</option><option value="shortlisted">Shortlist</option><option value="offer">Offer</option><option value="hired">Hire</option><option value="rejected">Reject</option></select><button class="secondary" onclick="showAI('${a.id}')">AI summary</button><button class="secondary" onclick="scheduleInterview('${a.id}')">Interview</button></div></td></tr>`).join('');$('content').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Candidate</th><th>Email</th><th>Stage</th><th>CV</th><th>Actions</th></tr></thead><tbody>${rows||'<tr><td colspan="5">No applications.</td></tr>'}</tbody></table></div>`}catch(e){toast(e.message)}}
async function changeStage(id,status){if(!status)return;try{await api(`/recruiter/applications/${id}/stage`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});toast('Stage updated');}catch(e){toast(e.message)}}
async function scheduleInterview(id){const date=prompt('Interview date (YYYY-MM-DD):');const time=prompt('Interview time (HH:MM):');const meeting=prompt('Meeting link or location:');if(!date||!time||!meeting)return;const data=meeting.startsWith('http')?{interview_date:date,interview_time:time,meeting_url:meeting}:{interview_date:date,interview_time:time,location:meeting};try{await api(`/recruiter/applications/${id}/interview`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});toast('Interview scheduled')}catch(e){toast(e.message)}}
async function showAI(id){try{const d=await api(`/recruiter/applications/${id}/ai-summary`);toast(d.status==='completed'?'AI summary is available':'Summary not available')}catch(e){try{await api(`/recruiter/applications/${id}/ai-summary/retry`,{method:'POST'});toast('AI summary retry requested')}catch(err){toast(err.message)}}}
async function checkApi(){try{await fetch(API+'/');$('apiStatus').textContent='API connected'}catch{$('apiStatus').textContent='API offline'}}
checkApi();boot();

